/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.TeknisiDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ryumaaa
 */
public class Teknisi extends javax.swing.JPanel {

    /**
     * Creates new form Teknisi
     */
    public Teknisi() {
        initComponents();
        loadTableTeknisi();
        generateKodeTeknisi();
        tkodeteknisi.disable();
    }

    private void loadTableTeknisi() {

        DefaultTableModel model
                = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Kode");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telepon");
        model.addColumn("Divisi");
        model.addColumn("Jabatan");
        model.addColumn("Status");

        TeknisiDAO dao = new TeknisiDAO();

        for (model.Teknisi t : dao.getAll()) {

            model.addRow(new Object[]{
                t.getIdTeknisi(),
                t.getKodeTeknisi(),
                t.getNamaTeknisi(),
                t.getJenisKelamin(),
                t.getNoTelepon(),
                t.getDivisi(),
                t.getJabatan(),
                t.getStatus()
            });
        }

        tblteknisi.setModel(model);
    }

    private void generateKodeTeknisi() {

        TeknisiDAO dao = new TeknisiDAO();

        String kode = dao.generateKode();

        tkodeteknisi.setText(kode);
    }

    private void cariTeknisi(String keyword) {

        DefaultTableModel model
                = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Kode");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telepon");
        model.addColumn("Divisi");
        model.addColumn("Jabatan");
        model.addColumn("Status");

        TeknisiDAO dao = new TeknisiDAO();

        for (model.Teknisi t : dao.search(keyword)) {

            model.addRow(new Object[]{
                t.getIdTeknisi(),
                t.getKodeTeknisi(),
                t.getNamaTeknisi(),
                t.getJenisKelamin(),
                t.getNoTelepon(),
                t.getDivisi(),
                t.getJabatan(),
                t.getStatus()
            });
        }

        tblteknisi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void resetForm() {

        tkodeteknisi.setText("");
        tnamateknisi.setText("");

        tjeniskelamin.setSelectedIndex(0);

        ttempatlahir.setText("");

        ttanggallahir.setDate(null);

        talamat.setText("");

        tnotelp.setText("");

        temail.setText("");

        tdivisi.setText("");

        tjabatan.setSelectedItem("");

        ttanggalmasuk.setDate(null);

        tstatus.setSelectedIndex(0);

        tkodeteknisi.requestFocus();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tkodeteknisi = new javax.swing.JTextField();
        tnamateknisi = new javax.swing.JTextField();
        tjeniskelamin = new javax.swing.JComboBox<>();
        ttempatlahir = new javax.swing.JTextField();
        tnotelp = new javax.swing.JTextField();
        tdivisi = new javax.swing.JTextField();
        tjabatan = new javax.swing.JComboBox<>();
        tstatus = new javax.swing.JComboBox<>();
        ttanggallahir = new com.toedter.calendar.JDateChooser();
        ttanggalmasuk = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblteknisi = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        talamat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Kode Teknisi");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nama Teknisi");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Tempat Lahir");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("No Telp");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Divisi");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Jabatan");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Alamat");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Status ");

        tkodeteknisi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tkodeteknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkodeteknisiActionPerformed(evt);
            }
        });

        tnamateknisi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tjeniskelamin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih jenis kelamin", "Laki-laki", "Perempuan" }));
        tjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjeniskelaminActionPerformed(evt);
            }
        });

        ttempatlahir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tnotelp.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tnotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnotelpActionPerformed(evt);
            }
        });

        tdivisi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tdivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdivisiActionPerformed(evt);
            }
        });

        tjabatan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih jabatan", "Manager IT", "SPV IT", "Staff" }));

        tstatus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih status", "Aktif", "Tidak aktif" }));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Tanggal Masuk");

        tblteknisi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblteknisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblteknisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblteknisiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblteknisi);

        btnsimpan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Cari");

        tcari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
        });

        talamat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Email");

        temail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(433, 433, 433))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel10))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tkodeteknisi)
                                    .addComponent(tnamateknisi, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(tjeniskelamin, 0, 360, Short.MAX_VALUE)
                                    .addComponent(talamat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tdivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tjabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(25, 25, 25)
                                        .addComponent(ttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tstatus, 0, 360, Short.MAX_VALUE)
                                    .addComponent(temail))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(10, 10, 10)
                                        .addComponent(ttanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13)
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jSeparator3)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tkodeteknisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5))
                            .addComponent(ttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnamateknisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tdivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ttanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        resetForm();
        generateKodeTeknisi();
        btnsimpan.setVisible(true);

    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String kode
                = tkodeteknisi.getText().trim();

        if (kode.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Pilih data terlebih dahulu");

            return;
        }

        int konfirmasi
                = JOptionPane.showConfirmDialog(
                        this,
                        "Yakin ingin menghapus Teknisi Dengan Kode "
                        + kode + "?",
                        "Konfirmasi Hapus",
                        JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {

            TeknisiDAO dao = new TeknisiDAO();

            if (dao.delete(kode)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Data berhasil dihapus");

                loadTableTeknisi();

                resetForm();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Data gagal dihapus");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if (tkodeteknisi.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Pilih data terlebih dahulu dari tabel");

            return;
        }

        model.Teknisi t = new model.Teknisi();

        t.setKodeTeknisi(
                tkodeteknisi.getText().trim());

        t.setNamaTeknisi(
                tnamateknisi.getText().trim());

        t.setJenisKelamin(
                tjeniskelamin.getSelectedItem().toString());

        t.setTempatLahir(
                ttempatlahir.getText().trim());

        t.setTanggalLahir(
                ttanggallahir.getDate() != null
                ? new java.sql.Date(
                        ttanggallahir.getDate().getTime())
                : null);

        t.setAlamat(
                talamat.getText().trim());

        t.setNoTelepon(
                tnotelp.getText().trim());

        t.setEmail(
                temail.getText().trim());

        t.setDivisi(
                tdivisi.getText().trim());

        t.setJabatan(
                tjabatan.getSelectedItem().toString());

        t.setTanggalMasuk(
                ttanggalmasuk.getDate() != null
                ? new java.sql.Date(
                        ttanggallahir.getDate().getTime())
                : null);

        t.setStatus(
                tstatus.getSelectedItem().toString());

        TeknisiDAO dao = new TeknisiDAO();

        if (dao.update(t)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Data teknisi berhasil diupdate");

            loadTableTeknisi();

            resetForm();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Data teknisi gagal diupdate");
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tdivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdivisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdivisiActionPerformed

    private void tnotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnotelpActionPerformed

    private void tjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjeniskelaminActionPerformed

    private void tkodeteknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkodeteknisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkodeteknisiActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (tkodeteknisi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Kode Teknisi tidak boleh kosong");
            return;
        }

        if (tnamateknisi.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Nama Teknisi tidak boleh kosong");
            return;
        }

        model.Teknisi t = new model.Teknisi();

        t.setKodeTeknisi(tkodeteknisi.getText().trim());

        t.setNamaTeknisi(tnamateknisi.getText().trim());

        t.setJenisKelamin(tjeniskelamin.getSelectedItem().toString());

        t.setTempatLahir(ttempatlahir.getText().trim());

        t.setTanggalLahir(
                ttanggallahir.getDate() != null
                ? new java.sql.Date(
                        ttanggallahir.getDate().getTime())
                : null);

        t.setAlamat(talamat.getText().trim());

        t.setNoTelepon(tnotelp.getText().trim());

        t.setEmail(temail.getText().trim());

        t.setDivisi(tdivisi.getText().trim());

        t.setJabatan(tjabatan.getSelectedItem().toString());

        t.setTanggalMasuk(
                ttanggalmasuk.getDate() != null
                ? new java.sql.Date(
                        ttanggalmasuk.getDate().getTime())
                : null);

        t.setStatus(tstatus.getSelectedItem().toString());

        TeknisiDAO dao = new TeknisiDAO();

        if (dao.insert(t)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Data Teknisi Berhasil Disimpan");

            resetForm();
            loadTableTeknisi();
            generateKodeTeknisi();
        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Data Teknisi Gagal Disimpan");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tblteknisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblteknisiMouseClicked
        int row = tblteknisi.getSelectedRow();

        if (row == -1) {
            return;
        }

        String kode
                = tblteknisi.getValueAt(row, 1).toString();

        TeknisiDAO dao
                = new TeknisiDAO();

        model.Teknisi t
                = dao.getByKode(kode);

        if (t != null) {

            tkodeteknisi.setText(
                    t.getKodeTeknisi());

            tnamateknisi.setText(
                    t.getNamaTeknisi());

            tjeniskelamin.setSelectedItem(
                    t.getJenisKelamin());

            ttempatlahir.setText(
                    t.getTempatLahir());

            ttanggallahir.setDate(
                    t.getTanggalLahir());

            talamat.setText(
                    t.getAlamat());

            tnotelp.setText(
                    t.getNoTelepon());

            temail.setText(
                    t.getEmail());

            tdivisi.setText(
                    t.getDivisi());

            tjabatan.setSelectedItem(
                    t.getJabatan());

            ttanggalmasuk.setDate(
                    t.getTanggalMasuk());

            tstatus.setSelectedItem(
                    t.getStatus());
        }
        btnsimpan.setVisible(false);
    }//GEN-LAST:event_tblteknisiMouseClicked

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        String keyword
                = tcari.getText().trim();

        if (keyword.isEmpty()) {

            loadTableTeknisi();

        } else {

            cariTeknisi(keyword);
        }
    }//GEN-LAST:event_tcariKeyPressed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField talamat;
    private javax.swing.JTable tblteknisi;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tdivisi;
    private javax.swing.JTextField temail;
    private javax.swing.JComboBox<String> tjabatan;
    private javax.swing.JComboBox<String> tjeniskelamin;
    private javax.swing.JTextField tkodeteknisi;
    private javax.swing.JTextField tnamateknisi;
    private javax.swing.JTextField tnotelp;
    private javax.swing.JComboBox<String> tstatus;
    private com.toedter.calendar.JDateChooser ttanggallahir;
    private com.toedter.calendar.JDateChooser ttanggalmasuk;
    private javax.swing.JTextField ttempatlahir;
    // End of variables declaration//GEN-END:variables
}
