/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import view.Dashboard;
import view.HasilPerangkingan;
import view.Kriteria;
import view.Login;
import view.PerbandinganKriteria;
import view.Report;
import view.Teknisi;
import view.User;

/**
 *
 * @author USER
 */
public class Main extends javax.swing.JFrame {

    int x, y;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        getTanggal();
        setJam();
//        if (Login.userLogin != null) {
//            lpengguna.setText(Login.userLogin.getnmLengkap());
//        }
    }

    private String getTanggal() {
        String pattern = "EEEE, dd/MMMM/YYYY";
        SimpleDateFormat tgl = new SimpleDateFormat(pattern, new Locale("id", "ID"));
        Date date = new Date();
        ltanggal.setText(tgl.format(date));
        return null;
    }

    public void setJam() {
        ActionListener taskPerformer = new ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";

                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String waktu = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                ljam.setText(waktu + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    public void setColor(JPanel p) {
        p.setBackground(new Color(51, 51, 51));
    }

    public void resetColor(JPanel p1) {
        p1.setBackground(new Color(51, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_sidebar = new javax.swing.JPanel();
        lpengguna = new javax.swing.JLabel();
        ltanggal = new javax.swing.JLabel();
        ljam = new javax.swing.JLabel();
        pbalternatif = new javax.swing.JPanel();
        palternatif = new javax.swing.JLabel();
        pbkriteria = new javax.swing.JPanel();
        pkriteria = new javax.swing.JLabel();
        pbnilaiKriteria = new javax.swing.JPanel();
        pnilaiKriteria = new javax.swing.JLabel();
        pbuser = new javax.swing.JPanel();
        pusers = new javax.swing.JLabel();
        pblogout = new javax.swing.JPanel();
        plogout = new javax.swing.JLabel();
        pbdashboard = new javax.swing.JPanel();
        pdashboard = new javax.swing.JLabel();
        pbhasilAkhir = new javax.swing.JPanel();
        phasilAkhir = new javax.swing.JLabel();
        pbReport = new javax.swing.JPanel();
        pReport = new javax.swing.JLabel();
        pn_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_sidebar.setBackground(new java.awt.Color(51, 51, 51));

        lpengguna.setBackground(new java.awt.Color(255, 255, 255));
        lpengguna.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lpengguna.setForeground(new java.awt.Color(255, 255, 255));
        lpengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-verified-account-25.png"))); // NOI18N
        lpengguna.setText("Pengguna");

        ltanggal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ltanggal.setForeground(new java.awt.Color(255, 255, 255));
        ltanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-date-25.png"))); // NOI18N
        ltanggal.setText("Tanggal");

        ljam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ljam.setForeground(new java.awt.Color(255, 255, 255));
        ljam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-stopwatch-25.png"))); // NOI18N
        ljam.setText("Jam");

        pbalternatif.setBackground(new java.awt.Color(51, 0, 0));
        pbalternatif.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        palternatif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        palternatif.setForeground(new java.awt.Color(255, 255, 255));
        palternatif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-spray-25.png"))); // NOI18N
        palternatif.setText("Data Alternatif");
        palternatif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                palternatifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                palternatifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                palternatifMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbalternatifLayout = new javax.swing.GroupLayout(pbalternatif);
        pbalternatif.setLayout(pbalternatifLayout);
        pbalternatifLayout.setHorizontalGroup(
            pbalternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbalternatifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(palternatif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbalternatifLayout.setVerticalGroup(
            pbalternatifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(palternatif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        pbkriteria.setBackground(new java.awt.Color(51, 0, 0));
        pbkriteria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pkriteria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pkriteria.setForeground(new java.awt.Color(255, 255, 255));
        pkriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-to-do-list-25.png"))); // NOI18N
        pkriteria.setText("Data Kriteria");
        pkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pkriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pkriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pkriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbkriteriaLayout = new javax.swing.GroupLayout(pbkriteria);
        pbkriteria.setLayout(pbkriteriaLayout);
        pbkriteriaLayout.setHorizontalGroup(
            pbkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbkriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbkriteriaLayout.setVerticalGroup(
            pbkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        pbnilaiKriteria.setBackground(new java.awt.Color(51, 0, 0));
        pbnilaiKriteria.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnilaiKriteria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pnilaiKriteria.setForeground(new java.awt.Color(255, 255, 255));
        pnilaiKriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-scorecard-25.png"))); // NOI18N
        pnilaiKriteria.setText("Perbandingan Kriteria");
        pnilaiKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnilaiKriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnilaiKriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnilaiKriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbnilaiKriteriaLayout = new javax.swing.GroupLayout(pbnilaiKriteria);
        pbnilaiKriteria.setLayout(pbnilaiKriteriaLayout);
        pbnilaiKriteriaLayout.setHorizontalGroup(
            pbnilaiKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbnilaiKriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnilaiKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );
        pbnilaiKriteriaLayout.setVerticalGroup(
            pbnilaiKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnilaiKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pbuser.setBackground(new java.awt.Color(51, 0, 0));
        pbuser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pusers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pusers.setForeground(new java.awt.Color(255, 255, 255));
        pusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-system-administrator-male-25.png"))); // NOI18N
        pusers.setText("Data User");
        pusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pusersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pusersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pusersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbuserLayout = new javax.swing.GroupLayout(pbuser);
        pbuser.setLayout(pbuserLayout);
        pbuserLayout.setHorizontalGroup(
            pbuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbuserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pusers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbuserLayout.setVerticalGroup(
            pbuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pusers, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pblogout.setBackground(new java.awt.Color(51, 0, 0));
        pblogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        plogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        plogout.setForeground(new java.awt.Color(255, 255, 255));
        plogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-shutdown-25.png"))); // NOI18N
        plogout.setText("Logout");
        plogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pblogoutLayout = new javax.swing.GroupLayout(pblogout);
        pblogout.setLayout(pblogoutLayout);
        pblogoutLayout.setHorizontalGroup(
            pblogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pblogoutLayout.setVerticalGroup(
            pblogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plogout, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pbdashboard.setBackground(new java.awt.Color(51, 0, 0));
        pbdashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pdashboard.setBackground(new java.awt.Color(255, 255, 255));
        pdashboard.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pdashboard.setForeground(new java.awt.Color(255, 255, 255));
        pdashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-dashboard-25.png"))); // NOI18N
        pdashboard.setText("Dashboard");
        pdashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbdashboardLayout = new javax.swing.GroupLayout(pbdashboard);
        pbdashboard.setLayout(pbdashboardLayout);
        pbdashboardLayout.setHorizontalGroup(
            pbdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbdashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbdashboardLayout.setVerticalGroup(
            pbdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pdashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        pbhasilAkhir.setBackground(new java.awt.Color(51, 0, 0));
        pbhasilAkhir.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        phasilAkhir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phasilAkhir.setForeground(new java.awt.Color(255, 255, 255));
        phasilAkhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-plus-minus-25.png"))); // NOI18N
        phasilAkhir.setText("Hasil Akhir");
        phasilAkhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phasilAkhirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phasilAkhirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phasilAkhirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbhasilAkhirLayout = new javax.swing.GroupLayout(pbhasilAkhir);
        pbhasilAkhir.setLayout(pbhasilAkhirLayout);
        pbhasilAkhirLayout.setHorizontalGroup(
            pbhasilAkhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbhasilAkhirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phasilAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbhasilAkhirLayout.setVerticalGroup(
            pbhasilAkhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phasilAkhir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pbReport.setBackground(new java.awt.Color(51, 0, 0));
        pbReport.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pReport.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pReport.setForeground(new java.awt.Color(255, 255, 255));
        pReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-pdf-25.png"))); // NOI18N
        pReport.setText("Laporan");
        pReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pbReportLayout = new javax.swing.GroupLayout(pbReport);
        pbReport.setLayout(pbReportLayout);
        pbReportLayout.setHorizontalGroup(
            pbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbReportLayout.setVerticalGroup(
            pbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbalternatif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pbkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pbnilaiKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pbuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pblogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pbdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pbhasilAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lpengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ltanggal)
                    .addComponent(ljam))
                .addContainerGap())
            .addComponent(pbReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lpengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ltanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ljam)
                .addGap(15, 15, 15)
                .addComponent(pbdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbalternatif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbnilaiKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbhasilAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pblogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_header.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistem Pendukung Keputusan Menggunakan Metode AHP");

        javax.swing.GroupLayout pn_headerLayout = new javax.swing.GroupLayout(pn_header);
        pn_header.setLayout(pn_headerLayout);
        pn_headerLayout.setHorizontalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_headerLayout.setVerticalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pn_content.setBackground(new java.awt.Color(255, 255, 255));

        pn_dasar.setBackground(new java.awt.Color(255, 255, 255));
        pn_dasar.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contentLayout.createSequentialGroup()
                .addComponent(pn_dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_contentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pn_dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pn_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void palternatifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palternatifMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new Teknisi());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_palternatifMouseClicked

    private void palternatifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palternatifMouseEntered
        setColor(pbalternatif);
    }//GEN-LAST:event_palternatifMouseEntered

    private void palternatifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palternatifMouseExited
        resetColor(pbalternatif);
    }//GEN-LAST:event_palternatifMouseExited

    private void pkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkriteriaMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new Kriteria());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_pkriteriaMouseClicked

    private void pkriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkriteriaMouseEntered
        setColor(pbkriteria);
    }//GEN-LAST:event_pkriteriaMouseEntered

    private void pkriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pkriteriaMouseExited
        resetColor(pbkriteria);
    }//GEN-LAST:event_pkriteriaMouseExited

    private void pnilaiKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnilaiKriteriaMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new PerbandinganKriteria());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_pnilaiKriteriaMouseClicked

    private void pnilaiKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnilaiKriteriaMouseEntered
        setColor(pbnilaiKriteria);
    }//GEN-LAST:event_pnilaiKriteriaMouseEntered

    private void pnilaiKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnilaiKriteriaMouseExited
        resetColor(pbnilaiKriteria);
    }//GEN-LAST:event_pnilaiKriteriaMouseExited

    private void pusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pusersMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new User());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_pusersMouseClicked

    private void pusersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pusersMouseEntered
        setColor(pbuser);
    }//GEN-LAST:event_pusersMouseEntered

    private void pusersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pusersMouseExited
        resetColor(pbuser);
    }//GEN-LAST:event_pusersMouseExited

    private void plogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMouseClicked
      int close = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Logout?","Select Option",JOptionPane.YES_NO_OPTION);
        if(close==0) {
            Login log = new Login();
            log.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_plogoutMouseClicked

    private void plogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMouseEntered
        setColor(pblogout);
    }//GEN-LAST:event_plogoutMouseEntered

    private void plogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMouseExited
        resetColor(pblogout);
    }//GEN-LAST:event_plogoutMouseExited

    private void pdashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdashboardMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new Dashboard());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_pdashboardMouseClicked

    private void pdashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdashboardMouseEntered
        setColor(pbdashboard);
    }//GEN-LAST:event_pdashboardMouseEntered

    private void pdashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdashboardMouseExited
        resetColor(pbdashboard);
    }//GEN-LAST:event_pdashboardMouseExited

    private void phasilAkhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phasilAkhirMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new HasilPerangkingan());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_phasilAkhirMouseClicked

    private void phasilAkhirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phasilAkhirMouseEntered
        setColor(pbhasilAkhir);
    }//GEN-LAST:event_phasilAkhirMouseEntered

    private void phasilAkhirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phasilAkhirMouseExited
        resetColor(pbhasilAkhir);
    }//GEN-LAST:event_phasilAkhirMouseExited

    private void pReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pReportMouseClicked
        pn_dasar.removeAll();   
        pn_dasar.add(new Report());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_pReportMouseClicked

    private void pReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pReportMouseEntered
        setColor(pbReport);
    }//GEN-LAST:event_pReportMouseEntered

    private void pReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pReportMouseExited
        resetColor(pbReport);
    }//GEN-LAST:event_pReportMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_dasar.removeAll();
        pn_dasar.add(new Dashboard());
        pn_dasar.repaint();
        pn_dasar.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ljam;
    private javax.swing.JLabel lpengguna;
    private javax.swing.JLabel ltanggal;
    private javax.swing.JLabel pReport;
    private javax.swing.JLabel palternatif;
    private javax.swing.JPanel pbReport;
    private javax.swing.JPanel pbalternatif;
    private javax.swing.JPanel pbdashboard;
    private javax.swing.JPanel pbhasilAkhir;
    private javax.swing.JPanel pbkriteria;
    private javax.swing.JPanel pblogout;
    private javax.swing.JPanel pbnilaiKriteria;
    private javax.swing.JPanel pbuser;
    private javax.swing.JLabel pdashboard;
    private javax.swing.JLabel phasilAkhir;
    private javax.swing.JLabel pkriteria;
    private javax.swing.JLabel plogout;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_header;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JLabel pnilaiKriteria;
    private javax.swing.JLabel pusers;
    // End of variables declaration//GEN-END:variables
}
